/* Generated by RbxNetIdGen */

export const enum RemoteId {
	interactWithStructureSlot = "638b68c3-2cca-4160-9359-78e7412276e2",
	pickupItem = "05c31fcf-7e4a-484e-9770-0fb683566eed",
	fireBullet = "94e8df20-a758-49b5-bc24-df4e99795a1e",
}
