/* Generated by RbxNetIdGen */

export const enum RemoteId {
    interactWithStructureSlot = "62b973fb-6b44-4ffd-bf60-ca70acd5b14e",
    pickupItem = "9bf8d6f1-927a-474a-8c17-64b352d7f326",
    fireBullet = "c8038eff-eae6-40bd-83e6-55a40e1893b1",
    receiveBullet = "66f3eab2-b4db-404c-8df9-d495d57e54a3",
    flushIds = "b9720854-0586-456a-b422-c64d27f3152d",
    getIds = "a54bcd72-1aae-48b5-9ffd-12e5714ead26"
}
