/* Generated by RbxNetIdGen */

export const enum RemoteId {
	interactWithStructureSlot = "f93e8004-7985-4619-b12c-f275bbdfc42c",
	pickupItem = "a421cac8-0525-4280-9fd6-d5a6887b209e",
	fireBullet = "e50febfe-3d21-414d-86fe-bba13d9d3d45",
	receiveBullet = "406360d8-c834-4719-84e0-6ee14bfb3058",
}
